[theme]
# Cor primária que você já tinha (botões, campos, etc.)
primaryColor="#8A2BE2"

# --- MUDANÇA AQUI ---
# Cor de fundo principal da página. Usei um lilás bem suave.
backgroundColor="#F2EBFD"

# Cor de fundo de elementos secundários (como a área do formulário).
# Um tom um pouco diferente para dar um leve contraste.
secondaryBackgroundColor="#E6E0F8"

# Cor do texto (mantemos escura para boa leitura)
textColor="#31333F"

# Fonte
font="sans serif"
