[theme]
# Cor primária usada nos elementos interativos (botões, etc.)
primaryColor="#8A2BE2" # Um tom de roxo (BlueViolet)

# Cor de fundo principal
backgroundColor="#F0F2F6" # Um cinza bem claro, para não cansar a vista

# Cor de fundo de elementos secundários (como a barra lateral)
secondaryBackgroundColor="#E6E0F8" # Um roxo bem clarinho

# Cor do texto
textColor="#31333F"

# Fonte
font="sans serif"
